# Generated by Django 2.0 on 2018-06-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180620_0210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoy',
            new_name='Category',
        ),
    ]
